= Conclusion <conclusion>

Ce travail de Bachelor avait pour but de concevoir, développer et tester un nouveau serious game autour du "Ethical Hacking", en continuité avec la plateforme _CyberGame_ et les scénarios initiaux "Shana a disparu" et "Sauve la Terre de l'arme galactique !". L’objectif principal était de proposer une expérience pédagogique immersive, qui combine une narration captivante et des défis techniques, afin de sensibiliser un public large aux enjeux de la cybersécurité.

Grâce à la conception et élaboration du scénario réaliste "Fuite de données dans le Centre Hospitalier Horizon Santé", nous avons abordé la problématique en s'inspirant d'incidents réels d'attaques par ransomware sur des infrastructures critiques. Ce scénario intègre sept challenges progressifs. À travers ces challenges techniques, les joueur·euse·s découvrent l'ensemble d'une réponse à un incident de ce type, avec de l'analyse d'emails de phishing à l'exploitation de vulnérabilités web, en passant par la cryptanalyse, le reverse engineering, une attaque XSS pour supprimer les dossiers compromettants et les opérations défensives. Cette progression permet d'aborder des compétences variées en cybersécurité tout en maintenant un fil narratif engageant mais aussi afin de s’adresser aussi bien aux débutant·e·s qu’aux utilisateur·trice·s plus expérimenté·e·s.

L'implémentation technique c'est appuyée sur l'architecture existante de _CyberGame_ , en y intégrant les fonctionnalités spécifiques du nouveau scénario. L'intégration de nouveaux outils pédagogiques, comme l'IDE Python embarqué avec Pyodide, les terminaux interactifs et le système de bot automatisé pour le challenge XSS, ont permis de renforcer l'expérience d'apprentissage avec de nouveaux types de challenges. La gestion sécurisée des flags via MongoDB et l'utilisation de Docker pour isoler les environnements garantissent à la fois la robustesse technique et l'intégrité du jeu.\
Enfin, en ce qui concerne les éléments d'amélioration au niveau de l'implémentation, le challenge 6, qui utilise un bot automatisé, présente également des problèmes techniques de gestion des cookies qui devront être corrigés pour garantir son bon fonctionnement.

Les phases de tests unitaires et utilisateurs ont confirmé la pertinence de l’approche. Les tests utilisateurs ont révélé des résultats assez différents selon le niveau des participant·e·s. Les profils avancés ont beaucoup aimé la diversité des challenges et l'immersion à l'aide de l'histoire, ce qui leur a permis de progresser de manière fluide à travers les différentes étapes. Les débutant·e·s, malgré qu'ils ont rencontré plus de difficultés, ont aussi montré une satisfaction pendant de la résolution des défis, ce qui a permis de confirmer la pertinence de l'approche pédagogique. Ces retours ont mis en évidence les points forts du jeu tout en identifiant plusieurs axes d'amélioration, notamment concernant la clarté des consignes, la simplification des indices avec une meilleure gradation et une meilleure intégration de la boîte à outils. Néanmoins, certaines limites persistent. La difficulté de réaliser un bon équilibrage entre les profils débutants et avancés reste complexe, et quelques challenges nécessitent encore des ajustements pour éviter des blocages prolongés. La densité du contenu de la boîte à outils pourrait être améliorée, et l'intégration de fonctionnalités de suivi de progression pourrait enrichir l'expérience globale des joueur·euse·s. 

Il est important de souligner que ce projet a été réalisé dans une version de 2020 de la plateforme _CyberGame_. Par conséquent, certaines parties de l'implémentation décrites dans ce rapport ne sont plus directement applicables à la version actuelle du site et des éléments d'améliorations ont déjà été pris en compte. Néanmoins, les concepts pédagogiques, le scénario développé et les mécanismes de jeu restent pertinents et peuvent être adaptés à la nouvelle architecture.


En conclusion, ce projet montre donc l'importance de la formation en sécurité informatique face à la multiplication des cyberattaques ciblant les infrastructures critiques et le potentiel des serious games comme outil de sensibilisation à la cybersécurité. Grâce à la combinaison d'une narration immersive et de défis techniques, cela permet d'offrir une alternative ludique aux formations traditionnelles tout en transmettant des compétences concrètes. La plateforme permet de renforcer cet apprentissage en offrant un environnement interactif et motivant. Le scénario "Fuite de données dans le Centre Hospitalier Horizon Santé" constitue une base solide pour de futures évolutions, que ce soit par l'ajout de nouveaux challenges, l'amélioration des mécanismes de progression, ... Il rappelle aussi l'importance cruciale de la cybersécurité dans notre société, où les attaques informatiques peuvent avoir des conséquences graves sur des infrastructures publiques essentielles et la protection des personnes. 
