= État de l'art <etatdelart>

Ce chapitre a pour objectif à explorer, comprendre et poser les différentes bases concernant les divers sujets abordés dans ce travail de Bachelor. Il s'agit de comprendre les enjeux, les défis et les solutions existantes dans le domaine de la cybersécurité, en particulier à travers l'utilisation de serious games et d'approches pédagogiques innovantes.

== Amélioration des compétences en cybersécurité <compétences-cybersécurité>

Différentes enquêtes et études montrent que la sensibilisation et la formation en cybersécurité sont essentielles pour réduire les risques liés aux cyberattaques. Les utilisateur·trice·s, qu'ils soient novices ou expérimentés, doivent être conscients des menaces potentielles et des bonnes pratiques à adopter. D'autant que des enquêtes annuelles confirment un manque d'environ 4,8 millions de professionnels de la cybersécurité dans le monde, ce qui souligne l'importance de former et de sensibiliser un plus grand nombre de personnes @2024ISC2Cybersecurity. D'autant plus que selon 64% des professionnels, les déficits de compétences en cybersécurité ont un impact négatif plus important qu'une pénurie de personnel. Fortinet montre que 70% des entreprises des incidents graves de cybersécurité sont dus à des erreurs humaines, ce qui met encore plus en avant l'importance de la formation et de la sensibilisation @fortinetFortinet2024Cybersecurity2024.

== Écosystèmes existants <écosystèmes-existants>
Actuellement, il existe plusieurs plateformes et écosystèmes qui proposent des environnements d'apprentissage en cybersécurité. Ces plateformes offrent des défis variés, allant de la simple sensibilisation à des scénarios plus complexes nécessitant des compétences techniques avancées, comme les cyber-ranges. Parmi les outils les plus connues, nous retrouvons beaucoup de CTF comme "Hack The Box" @HackBox1, "TryHackMe" @TryHackMeSimpleCTF et "RootMe" @BienvenueRootMe. Ces plateformes permettent aux utilisateur·trice·s de pratiquer leurs compétences dans un environnement sécurisé et contrôlé. Les autres outils et techniques sont moins connus, mais ils sont tout aussi importants pour la sensibilisation et la formation en cybersécurité. Parmi eux, nous pouvons citer les cyber-ranges académiques et industriels, les plateformes ouvertes de type CTF, les outils et techniques de sensibilisation à la cybersécurité, ainsi que les serious games, jeux narratifs et pédagogiques.

=== Cyber-ranges académiques / industriels <cyber-ranges>
Les cyber-ranges sont des environnements simulés qui permettent aux utilisateur·trice·s de pratiquer leurs compétences en cybersécurité dans un cadre réaliste @WhatCyberRange. Ils sont souvent utilisés par les institutions académiques et les entreprises pour former leurs employés et étudiants. Ces environnements offrent une expérience immersive, permettant aux utilisateur·trice·s de travailler sur des scénarios réels et de développer leurs compétences en résolution de problèmes mais aussi pratiquer différents types d'attaques. Ces cyber-ranges vont permettre de tester la mise en place des défenses et d’identifier des vulnérabilités potentielles sans compromettre la sécurité de vrais systèmes @QuestceQuunCyber2024a. Ces plateformes sont surtout utilisées pour des formations avancées et des exercices de simulations pour la Blue Team et donc ne sont pas accessibles à tous. La @cyber-range-imgs permet de comprendre le fonctionnement d'un cyber-range et son organisation. \
"Shana a disparu" n'a pas du tout cet objectif. En effet, son but est de sensibiliser et former les utilisateur·trice·s aux bases de la cybersécurité, en leur permettant de découvrir les techniques d'ethical hacking grâce à une approche narrative immersive. Les cyber-ranges sont donc plus adaptés pour des formations avancées et des exercices de simulations pour la Blue Team, tandis que "Shana a disparu" est destiné à un large public, allant des débutant·e·s aux personnes ayant déjà des connaissances en sécurité informatique.
#figure(
  image("imgs/cyber-range.png"),
  caption: [Schéma d'un cyber-range @WhatCyberRange],
)<cyber-range-imgs>


=== Plateformes ouvertes CTF <plateformes-ctf>
Les plateformes ouvertes de type CTF (Capture The Flag) sont des environnements d'apprentissage interactifs qui permettent aux utilisateur·trice·s de résoudre des défis de cybersécurité. Ces plateformes sont souvent utilisées dans le cadre de compétitions, mais elles peuvent également servir de ressources pédagogiques pour les étudiants et les professionnels souhaitant améliorer leurs compétences en cybersécurité. Elles offrent une variété de défis, allant de la simple cryptographie à des scénarios plus complexes impliquant l'exploitation de vulnérabilités. 
#figure(
  image("imgs/rootme-challenge.png"),
  caption: [Page des challenges de RootMe @BienvenueRootMe],
)<rootme-challenge-imgs>
A la différence des serious games, ces plateformes sont souvent plus techniques et nécessitent des compétences avancées en cybersécurité. Ils se présentent souvent sous la forme de compétitions où les participant·e·s tentent de résoudre des défis techniques pour obtenir une drapeau (flag) cachés dans des systèmes vulnérables @CTFHackingGuide. Ils sont donc moins accessibles aux débutant·e·s et peuvent être compliquées pour ceux qui n'ont pas de formation préalable en sécurité informatique. De plus, chaque challenge est souvent isolé, par catégorie et ne propose pas une histoire narrative immersive, comme le montre la @rootme-challenge-imgs. Ces plateformes sont donc plus adaptées aux utilisateur·trice·s ayant déjà des connaissances en sécurité informatique et souhaitant approfondir leurs compétences techniques.

=== Outils et techniques de sensibilisation à la cybersécurité <outils-sensibilisation>
Il existe de nombreux outils et techniques pour sensibiliser les utilisateur·trice·s à la cybersécurité. Parmi les plus courants, on trouve les formations en ligne, les ateliers pratiques et les simulations d'attaques, comme par exemple "SoSafe" @SensibilisationCybersecuriteGestion2022. Ces outils permettent aux utilisateur·trice·s de comprendre les menaces potentielles et d'apprendre à se protéger.\
La différence que nous pouvons observer avec le jeu "Shana a disparu" est que ces outils sont souvent plus théoriques et moins immersifs. Ils ne permettent pas aux utilisateur·trice·s de s'engager activement dans le processus d'apprentissage, ce qui peut limiter leur efficacité. En revanche, les serious games offrent une approche plus interactive et engageante, permettant aux utilisateur·trice·s de pratiquer leurs compétences dans un environnement sécurisé. De plus, généralement ces outils sont souvent destinés à des entreprises ou des organisations et sont donc payants, ce qui limite leur accessibilité pour le grand public.

=== Serious games, jeux narratifs et pédagogiques <serious-games>
Les serious games, ou jeux sérieux, sont des outils pédagogiques qui utilisent des éléments de jeu pour enseigner des concepts complexes. Ils sont particulièrement efficaces dans le domaine de la cybersécurité, car ils permettent aux utilisateur·trice·s de s'engager activement dans le processus d'apprentissage. Les jeux narratifs et pédagogiques offrent une approche immersive qui peut aider à renforcer la compréhension des concepts de cybersécurité et à améliorer la rétention des connaissances. Ces jeux peuvent simuler des scénarios réels, permettant aux utilisateur·trice·s de prendre des décisions et de voir les conséquences de leurs actions dans un environnement sécurisé.\
Il existe très peu de ces serious games en français, la plupart sont en anglais. De plus, la plupart des serious games sont payants et ne sont pas accessibles à tous, comme par exemple sur le site "UrbanGaming" @SeriousGameSecurite, "Shirudo" @ShirudoSeriousGame, ou encore "Cyber Wargame" @CyberWargameSerious. Ces entreprises proposent différents services, notamment des formations et des ateliers utilisant les serious games. Contrairement à "Shana a disparu", ils sont payants et ne sont pas accessibles à tous, ils sont souvent destinés à des entreprises ou des organisations, ce qui limite leur accessibilité pour le grand public.\

== Serious games comme solution <serious-games-solution>
Définis par _Clark Abt_ @abtSeriousGames1970, puis revue par _Mike Zyda_ @zydaVisualSimulationVirtual2005, les serious games sont #quote("un concours intellectuel, joué sur ordinateur selon des règles spécifiques, qui utilise le divertissement pour atteindre des objectifs de formation, d’éducation, de santé, de politique publique ou de communication stratégique.") (Zyda, From Visual Simulation to Virtual Reality to Games 2005, p.26) (citation traduite).
Les serious games sont de plus en plus utilisés comme solution pour sensibiliser et former les utilisateur·trice·s à la cybersécurité. Ils offrent une approche interactive et engageante qui permet leurs de pratiquer leurs compétences dans un environnement sécurisé. De plus, les serious games peuvent être adaptés à différents niveaux de compétences, ce qui les rend accessibles à un large public. Cependant, selon l'étude de _Chiu Yeong Ng_ et _Mohammad Khatim Bin Hasan_, la plupart des serious games existants ont été développés pour des utilisateurs avancés et ne sont pas adaptés aux débutants @ngCybersecuritySeriousGames2025. De plus, ils ont relevés que la majorité de ces jeux se focalisent plus sur des aspects techniques, tels que le piratages, les architectures réseaux, ..., que sur des aspects humains.
